<?php

namespace Database\Seeders;

use App\Models\Anggota;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class AnggotaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $anggota = [
            [
                'id' => strtolower((string) Str::ulid()),
                'nama' => 'A. SUNARNO RAHARJO',
                'tempat_lahir' => 'Sleman',
                'tanggal_lahir' => '1948-03-09',
                'nbm' => '1203 4888',
                'tahun_pembuatan' => 1988,
                'cabang' => 'Depok',
                'pdm' => 'Kab Sleman',
                'pwm' => 'DI Yogyakarta',
                'alamat' => 'Jl Kaliurang CT II B5 Tawangsari',
                'kabupaten_tinggal' => 'Kabupaten Sleman',
                'provinsi_tinggal' => 'DI Yogyakarta',
                'kelurahan' => 'Catur Tunggal',
                'profesi' => 'lain-lain',
                'no_hp' => '085101620025',
                'email' => null,
            ],

            [
                'id' => strtolower((string) Str::ulid()),
                'nama' => 'ABDUL BASHORI',
                'tempat_lahir' => 'Yogyakarta',
                'tanggal_lahir' => '1960-06-05',
                'nbm' => '1203 6017',
                'tahun_pembuatan' => 2017,
                'cabang' => 'Depok',
                'pdm' => 'Kab Sleman',
                'pwm' => 'Daerah Istimewa Yogyakarta',
                'alamat' => 'Jl Rawali 890 Pringgolayan',
                'kabupaten_tinggal' => 'Kab Sleman',
                'provinsi_tinggal' => 'Daerah Istimewa Yogyakarta',
                'profesi' => 'Pengusaha',
                'kelurahan' => 'Condongcatur',
                'no_hp' => null,
                'email' => null,
            ],
            [
                'id' => strtolower((string) Str::ulid()),
                'nama' => 'ABDUL GAPUR',
                'tempat_lahir' => 'Pasaman',
                'tanggal_lahir' => '1992-09-19',
                'nbm' => '1203 9213',
                'tahun_pembuatan' => 2013,
                'cabang' => 'Depok',
                'pdm' => 'Kab Sleman',
                'pwm' => 'Daerah Istimewa Yogyakarta',
                'alamat' => 'Jl Adisucipto 112 B',
                'kabupaten_tinggal' => 'Kab Sleman',
                'provinsi_tinggal' => 'Daerah Istimewa Yogyakarta',
                'profesi' => 'Lain-lain',
                'kelurahan' => 'Caturtunggal',
                'no_hp' => null,
                'email' => null,
            ],
            [
                'id' => strtolower((string) Str::ulid()),
                'nama' => 'ABDUL MALIK USMAN',
                'tempat_lahir' => 'Lamakera Flores Timur',
                'tanggal_lahir' => '1960-06-01',
                'nbm' => '1203 6095',
                'tahun_pembuatan' => 1995,
                'cabang' => 'Depok',
                'pdm' => 'Kab Sleman',
                'pwm' => 'Daerah Istimewa Yogyakarta',
                'alamat' => 'Denokan Rt 04/63',
                'kabupaten_tinggal' => 'Kab Sleman',
                'provinsi_tinggal' => 'Daerah Istimewa Yogyakarta',
                'profesi' => 'Dosen',
                'kelurahan' => 'Maguwoharjo',
                'no_hp' => '087838362255',
                'email' => 'el_usmani@yahoo.co.id',
            ],
            [
                'id' => strtolower((string) Str::ulid()),
                'nama' => 'ABDUL MUID BADRUN',
                'tempat_lahir' => 'Demak',
                'tanggal_lahir' => '1977-01-08',
                'nbm' => '1203 7723',
                'tahun_pembuatan' => 2023,
                'cabang' => 'Depok',
                'pdm' => 'Kab Sleman',
                'pwm' => 'Daerah Istimewa Yogyakarta',
                'alamat' => 'Jl Selokan Mataram No. 5 RT 02 RW 32',
                'kabupaten_tinggal' => 'Kab Sleman',
                'provinsi_tinggal' => 'Daerah Istimewa Yogyakarta',
                'profesi' => 'Lain-lain PT WOW MANAGEMENT INDONESIA',
                'kelurahan' => 'Condongcatur',
                'no_hp' => '0816600012',
                'email' => 'abdulmuidbadrun@gmail.com',
            ],
            [
                'id' => strtolower((string) Str::ulid()),
                'nama' => 'ABDUL MUIS',
                'tempat_lahir' => 'Tegal',
                'tanggal_lahir' => '1972-02-21',
                'nbm' => '1203 7207',
                'tahun_pembuatan' => 2007,
                'cabang' => 'Depok',
                'pdm' => 'Kab Sleman',
                'pwm' => 'Daerah Istimewa Yogyakarta',
                'alamat' => 'Ambarukmo Rt.05/02',
                'kabupaten_tinggal' => 'Kab Sleman',
                'provinsi_tinggal' => 'Daerah Istimewa Yogyakarta',
                'profesi' => 'Guru',
                'kelurahan' => 'Caturtunggal',
                'no_hp' => null,
                'email' => null,
            ],
            [
                'id' => strtolower((string) Str::ulid()),
                'nama' => 'ABDUL QUDDUS ZOHER',
                'tempat_lahir' => 'Palembang',
                'tanggal_lahir' => '1967-06-04',
                'nbm' => '1203 6793',
                'tahun_pembuatan' => 1993,
                'cabang' => 'Depok',
                'pdm' => 'Kab Sleman',
                'pwm' => 'Daerah Istimewa Yogyakarta',
                'alamat' => 'Jln.Wonosari Km.7 No.11 Rt.15 Mantup Baru',
                'kabupaten_tinggal' => 'Kab Bantul',
                'provinsi_tinggal' => 'Daerah Istimewa Yogyakarta',
                'profesi' => 'Guru',
                'kelurahan' => 'Baturetno',
                'no_hp' => null,
                'email' => null,
            ],
            [
                'id' => strtolower((string) Str::ulid()),
                'nama' => 'ACHMAD AFANDI',
                'tempat_lahir' => 'Surabaya',
                'tanggal_lahir' => '1971-07-30',
                'nbm' => '1203 7108',
                'tahun_pembuatan' => 2008,
                'cabang' => 'Depok',
                'pdm' => 'Kab Sleman',
                'pwm' => 'Daerah Istimewa Yogyakarta',
                'alamat' => 'Kembang RT 06 RW 62',
                'kabupaten_tinggal' => 'Kab Sleman',
                'provinsi_tinggal' => 'Daerah Istimewa Yogyakarta',
                'profesi' => 'Wiraswasta',
                'kelurahan' => 'Maguwoharjo',
                'no_hp' => '08121570450',
                'email' => null,
            ],
            [
                'id' => strtolower((string) Str::ulid()),
                'nama' => 'ACHMAD SULAIMAN',
                'tempat_lahir' => 'Banjarnegara',
                'tanggal_lahir' => '1955-10-10',
                'nbm' => '1203 5513',
                'tahun_pembuatan' => 2013,
                'cabang' => 'Depok',
                'pdm' => 'Kab Sleman',
                'pwm' => 'Daerah Istimewa Yogyakarta',
                'alamat' => 'Jl. Nusa Indah No.98B',
                'kabupaten_tinggal' => 'Kab Sleman',
                'provinsi_tinggal' => 'Daerah Istimewa Yogyakarta',
                'profesi' => 'Lain-lain',
                'kelurahan' => 'Condongcatur',
                'no_hp' => null,
                'email' => null,
            ],
            [
                'id' => strtolower((string) Str::ulid()),
                'nama' => 'ACHMADI BACHRI',
                'tempat_lahir' => 'Sukoharjo',
                'tanggal_lahir' => '1955-01-08',
                'nbm' => '1203 5504',
                'tahun_pembuatan' => 2004,
                'cabang' => 'Depok',
                'pdm' => 'Kab Sleman',
                'pwm' => 'Daerah Istimewa Yogyakarta',
                'alamat' => 'Purwosari',
                'kabupaten_tinggal' => 'Kab Sleman',
                'provinsi_tinggal' => 'Daerah Istimewa Yogyakarta',
                'profesi' => 'Dokter',
                'kelurahan' => 'Sinduadi',
                'no_hp' => null,
                'email' => null,
            ],


            [
                'id' => strtolower((string) Str::ulid()),
                'nama' => 'ADHITYA PONTICELLY',
                'tempat_lahir' => 'Subang',
                'tanggal_lahir' => '1986-03-09',
                'nbm' => '1203 8611',
                'tahun_pembuatan' => 2011,
                'cabang' => 'Depok',
                'pdm' => 'Kab Sleman',
                'pwm' => 'Daerah Istimewa Yogyakarta',
                'alamat' => 'Jl. Affandi Gg Menur 3 B',
                'kabupaten_tinggal' => 'Kab Sleman',
                'provinsi_tinggal' => 'Daerah Istimewa Yogyakarta',
                'profesi' => 'Guru',
                'kelurahan' => 'Caturtunggal',
                'no_hp' => null,
                'email' => null,
            ],
            [
                'id' => strtolower((string) Str::ulid()),
                'nama' => 'ADITYA HERMAWAN',
                'tempat_lahir' => 'Bantul',
                'tanggal_lahir' => '1992-11-16',
                'nbm' => '1203 9219',
                'tahun_pembuatan' => 2019,
                'cabang' => 'Depok',
                'pdm' => 'Kab Sleman',
                'pwm' => 'Daerah Istimewa Yogyakarta',
                'alamat' => 'Jl. Rajawali No.10',
                'kabupaten_tinggal' => 'Kab Sleman',
                'provinsi_tinggal' => 'Daerah Istimewa Yogyakarta',
                'profesi' => 'Guru SMP Muh 3 Depok',
                'kelurahan' => 'Caturtunggal',
                'no_hp' => '081903470122',
                'email' => null,
            ],
            [
                'id' => strtolower((string) Str::ulid()),
                'nama' => 'ADITYA PRATAMA',
                'tempat_lahir' => 'Yogyakarta',
                'tanggal_lahir' => '1988-01-30',
                'nbm' => '1203 8815',
                'tahun_pembuatan' => 2015,
                'cabang' => 'Depok',
                'pdm' => 'Kab Sleman',
                'pwm' => 'Daerah Istimewa Yogyakarta',
                'alamat' => 'Perum Kadisoka Pratama A6',
                'kabupaten_tinggal' => 'Kab Sleman',
                'provinsi_tinggal' => 'Daerah Istimewa Yogyakarta',
                'profesi' => 'Pegawai/Karyawan Suara Muhammadiyah',
                'kelurahan' => 'Kadisoka Purwamartani',
                'no_hp' => null,
                'email' => null,
            ],
            [
                'id' => strtolower((string) Str::ulid()),
                'nama' => 'ADRI DEWO BUDI PARAHITA',
                'tempat_lahir' => 'Yogyakarta',
                'tanggal_lahir' => '1980-02-05',
                'nbm' => '1203 8009',
                'tahun_pembuatan' => 2009,
                'cabang' => 'Depok',
                'pdm' => 'Kab Sleman',
                'pwm' => 'Daerah Istimewa Yogyakarta',
                'alamat' => 'Jalan Wulung 45 Papringan',
                'kabupaten_tinggal' => 'Kab Sleman',
                'provinsi_tinggal' => 'Daerah Istimewa Yogyakarta',
                'profesi' => 'Guru',
                'kelurahan' => 'Caturtunggal',
                'no_hp' => null,
                'email' => null,
            ],
            [
                'id' => strtolower((string) Str::ulid()),
                'nama' => 'AFIFUDDIN',
                'tempat_lahir' => 'Lamongan',
                'tanggal_lahir' => '1989-10-16',
                'nbm' => '1203 8910',
                'tahun_pembuatan' => 2010,
                'cabang' => 'Depok',
                'pdm' => 'Kab Sleman',
                'pwm' => 'Daerah Istimewa Yogyakarta',
                'alamat' => 'Bakungan RT 003/057',
                'kabupaten_tinggal' => 'Kab Sleman',
                'provinsi_tinggal' => 'Daerah Istimewa Yogyakarta',
                'profesi' => 'Wiraswasta SMK Muhammadiyah 1 Sleman',
                'kelurahan' => 'Wedomartani',
                'no_hp' => '085868786507',
                'email' => 'u.aviev@yahoo.com',
            ],
            [
                'id' => strtolower((string) Str::ulid()),
                'nama' => 'AGENG ASITARINI',
                'tempat_lahir' => 'Sleman',
                'tanggal_lahir' => '1994-12-13',
                'nbm' => '1203 9418',
                'tahun_pembuatan' => 2018,
                'cabang' => 'Depok',
                'pdm' => 'Kab Sleman',
                'pwm' => 'Daerah Istimewa Yogyakarta',
                'alamat' => 'Sarirejo Rt 06 Rw 47',
                'kabupaten_tinggal' => 'Kab Sleman',
                'provinsi_tinggal' => 'Daerah Istimewa Yogyakarta',
                'profesi' => 'Pegawai/Karyawan SMP Muh 1 Depok',
                'kelurahan' => 'Maguwoharjo',
                'no_hp' => '082339583351',
                'email' => 'asitarini@gmail.com',
            ],
            [
                'id' => strtolower((string) Str::ulid()),
                'nama' => 'AGUNG ASTUTI',
                'tempat_lahir' => 'Solo',
                'tanggal_lahir' => '1962-09-23',
                'nbm' => '1203 6294',
                'tahun_pembuatan' => 1994,
                'cabang' => 'Depok',
                'pdm' => 'Kab Sleman',
                'pwm' => 'Daerah Istimewa Yogyakarta',
                'alamat' => 'Perumahan Sawitsari E-7',
                'kabupaten_tinggal' => 'Kab Sleman',
                'provinsi_tinggal' => 'Daerah Istimewa Yogyakarta',
                'profesi' => 'Dosen UMY',
                'kelurahan' => 'Condong Catur',
                'no_hp' => null,
                'email' => null,
            ],
            [
                'id' => strtolower((string) Str::ulid()),
                'nama' => 'AGUNG PAMBUDI PRIHATMANTO',
                'tempat_lahir' => null,
                'tanggal_lahir' => '1982-05-31',
                'nbm' => '1203 8219',
                'tahun_pembuatan' => 2019,
                'cabang' => 'Depok',
                'pdm' => 'Kab Sleman',
                'pwm' => 'Daerah Istimewa Yogyakarta',
                'alamat' => 'Kayen RT 006 RW 044',
                'kabupaten_tinggal' => 'Kab Sleman',
                'provinsi_tinggal' => 'Daerah Istimewa Yogyakarta',
                'profesi' => 'Wiraswasta',
                'kelurahan' => 'Condong Catur',
                'no_hp' => null,
                'email' => null,
            ],
            [
                'id' => strtolower((string) Str::ulid()),
                'nama' => 'AGUNG PRIHANTORO',
                'tempat_lahir' => 'Purworejo',
                'tanggal_lahir' => '1972-09-12',
                'nbm' => '1203 7211',
                'tahun_pembuatan' => 2011,
                'cabang' => 'Depok',
                'pdm' => 'Kab Sleman',
                'pwm' => 'Daerah Istimewa Yogyakarta',
                'alamat' => 'Kradenan RT 12 RW 52 Ringinsari',
                'kabupaten_tinggal' => 'Kab Sleman',
                'provinsi_tinggal' => 'Daerah Istimewa Yogyakarta',
                'profesi' => 'Dosen Universitas Cokroaminoto Yogyakarta',
                'kelurahan' => 'Maguwoharjo',
                'no_hp' => '0811267506',
                'email' => 'zonaagung@yahoo.com',
            ],
            [
                'id' => strtolower((string) Str::ulid()),
                'nama' => 'AGUNG PURNOMO',
                'tempat_lahir' => 'Sleman',
                'tanggal_lahir' => '1982-05-09',
                'nbm' => '1203 8209',
                'tahun_pembuatan' => 2009,
                'cabang' => 'Depok',
                'pdm' => 'Kab Sleman',
                'pwm' => 'Daerah Istimewa Yogyakarta',
                'alamat' => 'Kayen',
                'kabupaten_tinggal' => 'Kab Sleman',
                'provinsi_tinggal' => 'Daerah Istimewa Yogyakarta',
                'profesi' => 'Pegawai/Karyawan',
                'kelurahan' => 'Condong Catur',
                'no_hp' => null,
                'email' => null,
            ],
            [
                'id' => strtolower((string) Str::ulid()),
                'nama' => 'AGUNG WIJAYANTO',
                'tempat_lahir' => 'Kebumen',
                'tanggal_lahir' => '1989-08-23',
                'nbm' => '1203 8916',
                'tahun_pembuatan' => 2016,
                'cabang' => 'Depok',
                'pdm' => 'Kab Sleman',
                'pwm' => 'Daerah Istimewa Yogyakarta',
                'alamat' => 'Pacitan',
                'kabupaten_tinggal' => 'Kab Pacitan',
                'provinsi_tinggal' => 'Jawa Timur',
                'profesi' => 'Pengusaha Konstruksi',
                'kelurahan' => 'Sidoharjo',
                'no_hp' => '085730101671',
                'email' => 'wijayantoagung23@gmail.com',
            ],
            [
                'id' => strtolower((string) Str::ulid()),
                'nama' => 'AGUS SUPRIYO',
                'tempat_lahir' => 'Klaten',
                'tanggal_lahir' => '1956-12-24',
                'nbm' => '1203 5607',
                'tahun_pembuatan' => 2007,
                'cabang' => 'Depok',
                'pdm' => 'Kab Sleman',
                'pwm' => 'Daerah Istimewa Yogyakarta',
                'alamat' => 'Jl. Swelobumi RT 01 RW 26 Pringgolayan Dabag',
                'kabupaten_tinggal' => 'Kab Sleman',
                'provinsi_tinggal' => 'Daerah Istimewa Yogyakarta',
                'profesi' => 'Lain-lain',
                'kelurahan' => 'Condong Catur',
                'no_hp' => null,
                'email' => null,
            ],
            [
                'id' => strtolower((string) Str::ulid()),
                'nama' => 'AGUSTIAN HARIS SYIHABUDDIN',
                'tempat_lahir' => 'Lampung',
                'tanggal_lahir' => '1991-08-04',
                'nbm' => '1203 9115',
                'tahun_pembuatan' => 2015,
                'cabang' => 'Depok',
                'pdm' => 'Kab Sleman',
                'pwm' => 'Daerah Istimewa Yogyakarta',
                'alamat' => 'Jl Laksda Adisucipto 112 B',
                'kabupaten_tinggal' => 'Kab Sleman',
                'provinsi_tinggal' => 'Daerah Istimewa Yogyakarta',
                'profesi' => 'Lain-lain',
                'kelurahan' => 'Catur Tunggal',
                'no_hp' => null,
                'email' => null,
            ],
            [
                'id' => strtolower((string) Str::ulid()),
                'nama' => 'AHMAD ABDUH HAQI',
                'tempat_lahir' => null,
                'tanggal_lahir' => '1989-05-24',
                'nbm' => '1203 8910',
                'tahun_pembuatan' => 2010,
                'cabang' => 'Depok',
                'pdm' => 'Kab Sleman',
                'pwm' => 'Daerah Istimewa Yogyakarta',
                'alamat' => 'Parakah 2/04',
                'kabupaten_tinggal' => 'Kab Magelang',
                'provinsi_tinggal' => 'Jawa Tengah',
                'profesi' => 'Pelajar/Mahasiswa',
                'kelurahan' => 'Bumiayu',
                'no_hp' => '081903865733',
                'email' => 'Haqie.ahmad@yahoo.co.id',
            ],
            [
                'id' => strtolower((string) Str::ulid()),
                'nama' => 'AHMAD AMALI KURNIAWAN',
                'tempat_lahir' => 'Nganjuk',
                'tanggal_lahir' => '1983-01-29',
                'nbm' => '1203 8308',
                'tahun_pembuatan' => 2008,
                'cabang' => 'Depok',
                'pdm' => 'Kab Sleman',
                'pwm' => 'Daerah Istimewa Yogyakarta',
                'alamat' => 'Jln. Semeru III/38 RT 003 RW I',
                'kabupaten_tinggal' => 'Kab Nganjuk',
                'provinsi_tinggal' => 'Jawa Timur',
                'profesi' => 'Lain-lain',
                'kelurahan' => 'Kedungombo',
                'no_hp' => '0818268617',
                'email' => 'amali@yahoo.com',
            ],


        ];
        Anggota::insert($anggota);
    }
}
